### ISSUE TITLE
Needs Solution

### ISSUE THREAD

**Issue by jmburges** [learn-co-curriculum/horizontal-profile#1]

**Comment by AnnJohn** [comment]
@jmburges This lab seems like a readme right now. Can be changed to a lab, but for now will mark the issues as stale and can revisit changing to a lab later.

**Comment by AnnJohn** [comment]
Iceboxing for now

**Comment by TOMalley104** [comment]
deadline: Friday 9/4

**Comment by TOMalley104** [comment]
solution created, @jmburges i dont know the best way to notify you but here I am

**Comment by AnnJohn** [comment]
@TOMalley104 Still figuring out the workflow but for now, assign both this issue and the PR to @jmburges and he'll reassign it back to you when he's done reviewing. Thanks!

**Comment by markedwardmurray** [comment]
resolved by https://github.com/learn-co-curriculum/horizontal-profile/pull/9
