### ISSUE TITLE
update readme to use willTransitionToSize: instead of willTransitionToTraitCollection:

### ISSUE THREAD

**Issue by TOMalley104** [learn-co-curriculum/horizontal-profile#8]

**Comment by AnnJohn** [comment]
Iceboxing for now

**Comment by markedwardmurray** [comment]
solution still uses `willTransitionToTraitCollection:`

@jmburges @misterfifths thoughts on using `willTransitionToSize:` instead?

**Comment by TOMalley104** [comment]
Students were going down the rabbit hole of traitCollection for not much pay off, so an executive decision was made– despite it not being in the solution branch yet, the README now mentions `size` instead.
